package com.mycompany.taskmanager.view;

import com.mycompany.taskmanager.model.User;
import javax.swing.SwingUtilities;

public class AdminPage extends javax.swing.JPanel {

    public User user;

    public AdminPage(User user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoffBTN = new javax.swing.JButton();
        listTasks = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        logoffBTN.setText("Logoff");
        logoffBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoffBTNActionPerformed(evt);
            }
        });

        listTasks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listTasks.setText("List Tasks");
        listTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTasksActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("List Users");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoffBTN)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(listTasks)
                .addGap(102, 102, 102)
                .addComponent(jButton1)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoffBTN)
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listTasks)
                    .addComponent(jButton1))
                .addGap(0, 409, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoffBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoffBTNActionPerformed
        MainFrame father = (MainFrame) SwingUtilities.getWindowAncestor(this);
        father.setContentPane(new Login());
        father.pack();
    }//GEN-LAST:event_logoffBTNActionPerformed

    private void listTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTasksActionPerformed
        MainFrame father = (MainFrame) SwingUtilities.getWindowAncestor(this);
        father.setContentPane(new ListTasks(user));
        father.pack();
    }//GEN-LAST:event_listTasksActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
MainFrame father = (MainFrame) SwingUtilities.getWindowAncestor(this);
        father.setContentPane(new ListUsers(user));
        father.pack();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton listTasks;
    private javax.swing.JButton logoffBTN;
    // End of variables declaration//GEN-END:variables
}
